### ISSUE TITLE
Common time to meet

### ISSUE THREAD

**Issue by mulliganaceous** [philippejlyu/CSC302#2]
As of now, we should establish more consistent communication and updates. As of now, the proposal is

**Monday:** LEC time
**Tuesday:** 9pm (15m)
**Wednesday:** 9pm (15m)
**Thursday:** 9pm (15m)
**Friday:** 9pm (1h)
**Saturday:** TBA
**Sunday:** 9pm (1h)

**Comment by philippejlyu** [comment]
As discussed in the previous meeting, we will be meeting 10PM nightly starting Monday Oct 31. If time permits, we will have the Monday meeting during the allocated lecture time slot.

**Comment by philippejlyu** [comment]
Please send this message in the chat instead of github. Messages here are not monitored as often
