### ISSUE TITLE
Firefox incompatibility

### ISSUE THREAD

**Issue by mulliganaceous** [philippejlyu/CSC302#34]
I am a Firefox user. There are some complications regarding the processing of the json.
Therefore, I am not able to see the results.

**Comment by philippejlyu** [comment]
Please send a screnshot of the console logs. Cannot repro on windows/mac on multiple browsers. Possibly an issue with your browser config.

**Comment by philippejlyu** [comment]
Possibly due to corrupted dataset instead of OS/Browser incompatibility
